FROM envoyproxy/envoy:v1.29.0

# admin web interface
EXPOSE 9901

# grpc json transcoder
EXPOSE 20000

COPY ./envoy.yaml        /etc/envoy/envoy.yaml
COPY ./descriptor_set.pb /etc/envoy/descriptor_set.pb

CMD ["--config-path", "/etc/envoy/envoy.yaml"]
